source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "graphql", "~> 2.1"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "debug", platforms: %i[mri windows]
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
end